# Feature Engineering

In [1]:
import numpy as np
import pandas as pd
import ast

In [2]:
movies = pd.read_csv("../data/tmdb_5000_movies.csv")
credits = pd.read_csv("../data/tmdb_5000_credits.csv")

# Merge datasets
movies = movies.merge(credits, on="title")

# Select useful columns
movies = movies[["movie_id", "title", "overview", "genres", "keywords", "cast", "crew"]]

# Remove missing values
movies.dropna(inplace=True)

# Remove duplicates if any
movies.drop_duplicates(inplace=True)

movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [3]:
movies.iloc[0]["genres"]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [4]:
# Create Function to Extract Names


def convert(obj):
    names = []

    for item in ast.literal_eval(obj):
        names.append(item["name"])

    return names

In [5]:
movies["genres"] = movies["genres"].apply(convert)
movies["keyworkds"] = movies["keywords"].apply(convert)

In [6]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,keyworkds
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[culture clash, future, space war, space colon..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[ocean, drug abuse, exotic island, east india ..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[spy, based on novel, secret agent, sequel, mi..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...","[dc comics, crime fighter, terrorist, secret i..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","[based on novel, mars, medallion, space travel..."

In [7]:
# Extract Top 3 Cast Members


def convert_cast(obj):
    names = []
    counter = 0

    for item in ast.literal_eval(obj):
        if counter != 3:
            names.append(item["name"])
            counter += 1

        else:
            break

    return names

In [8]:
movies["cast"] = movies["cast"].apply(convert_cast)

In [9]:
movies.iloc[0]["cast"]

['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver']

In [10]:
# Extract Director from Crew


def fetch_director(obj):
    directors = []

    for item in ast.literal_eval(obj):
        if item["job"] == "Director":
            directors.append(item["name"])
            break
    return directors

In [11]:
movies["crew"] = movies["crew"].apply(fetch_director)

In [12]:
movies.iloc[0]["crew"]

['James Cameron']

## Convert Overview into Word List

`overvies` is a sentence.

we need to convert it into a list of works.

In [13]:
movies["overview"] = movies["overview"].apply(lambda x: x.split())

In [14]:
movies.iloc[0]["overview"]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.']

## Remove Spaces Inside Names

Suppose we keep:

Sam Worthington

CountVectorizer will treat this as two separate words:

Sam

Worthington

In [15]:
def remove_space(word_list):
    new_list = []

    for word in word_list:
        new_list.append(word.replace(" ", ""))

    return new_list

In [16]:
movies["genres"] = movies["genres"].apply(remove_space)
movies["keywords"] = movies["keywords"].apply(remove_space)
movies["cast"] = movies["cast"].apply(remove_space)
movies["crew"] = movies["crew"].apply(remove_space)

In [17]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,keyworkds
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[[, {, "", i, d, "", :, , 1, 4, 6, 3, ,, , "", n,...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[culture clash, future, space war, space colon..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[[, {, "", i, d, "", :, , 2, 7, 0, ,, , "", n, a,...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[ocean, drug abuse, exotic island, east india ..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[[, {, "", i, d, "", :, , 4, 7, 0, ,, , "", n, a,...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[spy, based on novel, secret agent, sequel, mi..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[[, {, "", i, d, "", :, , 8, 4, 9, ,, , "", n, a,...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[dc comics, crime fighter, terrorist, secret i..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[[, {, "", i, d, "", :, , 8, 1, 8, ,, , "", n, a,...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[based on novel, mars, medallion, space travel..."

## Create the tags Column

overview + genres + keywords + cast + crew

In [18]:
movies["tags"] = (
    movies["overview"]
    + movies["genres"]
    + movies["keywords"]
    + movies["cast"]
    + movies["crew"]
)

In [19]:
movies.iloc[0]["tags"]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 'Action',
 'Adventure',
 'Fantasy',
 'ScienceFiction',
 '[',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '4',
 '6',
 '3',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'c',
 'u',
 'l',
 't',
 'u',
 'r',
 'e',
 '',
 'c',
 'l',
 'a',
 's',
 'h',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '2',
 '9',
 '6',
 '4',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'f',
 'u',
 't',
 'u',
 'r',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '3',
 '3',
 '8',
 '6',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 's',
 'p',
 'a',
 'c',
 'e',
 '',
 'w',
 'a',
 'r',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '3',
 '3',
 '8',
 '8',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 's',
 'p',
 'a',
 'c',
 'e',
 '',
 'c',
 'o',
 'l',
 'o',
 'n',
 'y',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '3',
 '6',
 '7',
 '9',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 's',
 'o',
 'c',
 'i',
 'e',
 't',
 'y',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '3',
 '8',
 '0',
 '1',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 's',
 'p',
 'a',
 'c',
 'e',
 '',
 't',
 'r',
 'a',
 'v',
 'e',
 'l',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '9',
 '6',
 '8',
 '5',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'f',
 'u',
 't',
 'u',
 'r',
 'i',
 's',
 't',
 'i',
 'c',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '9',
 '8',
 '4',
 '0',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'r',
 'o',
 'm',
 'a',
 'n',
 'c',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '9',
 '8',
 '8',
 '2',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 's',
 'p',
 'a',
 'c',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '9',
 '9',
 '5',
 '1',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'a',
 'l',
 'i',
 'e',
 'n',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '0',
 '1',
 '4',
 '8',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 't',
 'r',
 'i',
 'b',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '0',
 '1',
 '5',
 '8',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'a',
 'l',
 'i',
 'e',
 'n',
 '',
 'p',
 'l',
 'a',
 'n',
 'e',
 't',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '0',
 '9',
 '8',
 '7',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'c',
 'g',
 'i',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '1',
 '3',
 '9',
 '9',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'm',
 'a',
 'r',
 'i',
 'n',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '3',
 '0',
 '6',
 '5',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 's',
 'o',
 'l',
 'd',
 'i',
 'e',
 'r',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '4',
 '6',
 '4',
 '3',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'b',
 'a',
 't',
 't',
 'l',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '4',
 '7',
 '2',
 '0',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'l',
 'o',
 'v',
 'e',
 '',
 'a',
 'f',
 'f',
 'a',
 'i',
 'r',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '6',
 '5',
 '4',
 '3',
 '1',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'a',
 'n',
 't',
 'i',
 '',
 'w',
 'a',
 'r',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '9',
 '3',
 '5',
 '5',
 '4',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'p',
 'o',
 'w',
 'e',
 'r',
 '',
 'r',
 'e',
 'l',
 'a',
 't',
 'i',
 'o',
 'n',
 's',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '2',
 '0',
 '6',
 '6',
 '9',
 '0',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'm',
 'i',
 'n',
 'd',
 '',
 'a',
 'n',
 'd',
 '',
 's',
 'o',
 'u',
 'l',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '2',
 '0',
 '9',
 '7',
 '1',
 '4',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 '3',
 'd',
 '"',
 '}',
 ']',
 'SamWorthington',
 'ZoeSaldana',
 'SigourneyWeaver',
 'JamesCameron']

## Create Final DataFrame

In [20]:
new_df = movies[["movie_id", "title", "tags"]]

In [21]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [22]:
# Convert Tags List into String
new_df["tags"] = new_df["tags"].apply(lambda x: " ".join(x))

In [23]:
new_df.iloc[0]["tags"]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction [ { " i d " :  1 4 6 3 ,  " n a m e " :  " c u l t u r e  c l a s h " } ,  { " i d " :  2 9 6 4 ,  " n a m e " :  " f u t u r e " } ,  { " i d " :  3 3 8 6 ,  " n a m e " :  " s p a c e  w a r " } ,  { " i d " :  3 3 8 8 ,  " n a m e " :  " s p a c e  c o l o n y " } ,  { " i d " :  3 6 7 9 ,  " n a m e " :  " s o c i e t y " } ,  { " i d " :  3 8 0 1 ,  " n a m e " :  " s p a c e  t r a v e l " } ,  { " i d " :  9 6 8 5 ,  " n a m e " :  " f u t u r i s t i c " } ,  { " i d " :  9 8 4 0 ,  " n a m e " :  " r o m a n c e " } ,  { " i d " :  9 8 8 2 ,  " n a m e " :  " s p a c e " } ,  { " i d " :  9 9 5 1 ,  " n a m e " :  " a l i e n " } ,  { " i d " :  1 0 1 4 8 ,  " n a m e " :  " t r i b e " } ,  { " i d " :  1 0 1 5 8 ,  " n a m e " :  " a l i e n  p l a n e t " } ,  { " i d " :  1 0 9 8 7 ,  " n a m e " :  " c g i " } ,  { " i d " :  1 1 3 9 9 ,  " n a m e " :  " m a r i n e " } ,  { " i d " :  1 3 0 6 5 ,  " n a m e " :  " s o l d i e r " } ,  { " i d " :  1 4 6 4 3 ,  " n a m e " :  " b a t t l e " } ,  { " i d " :  1 4 7 2 0 ,  " n a m e " :  " l o v e  a f f a i r " } ,  { " i d " :  1 6 5 4 3 1 ,  " n a m e " :  " a n t i  w a r " } ,  { " i d " :  1 9 3 5 5 4 ,  " n a m e " :  " p o w e r  r e l a t i o n s " } ,  { " i d " :  2 0 6 6 9 0 ,  " n a m e " :  " m i n d  a n d  s o u l " } ,  { " i d " :  2 0 9 7 1 4 ,  " n a m e " :  " 3 d " } ] SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [24]:
# Convert Tags to Lowercase
new_df["tags"] = new_df["tags"].apply(lambda x: x.lower())

In [25]:
new_df.iloc[0]["tags"]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction [ { " i d " :  1 4 6 3 ,  " n a m e " :  " c u l t u r e  c l a s h " } ,  { " i d " :  2 9 6 4 ,  " n a m e " :  " f u t u r e " } ,  { " i d " :  3 3 8 6 ,  " n a m e " :  " s p a c e  w a r " } ,  { " i d " :  3 3 8 8 ,  " n a m e " :  " s p a c e  c o l o n y " } ,  { " i d " :  3 6 7 9 ,  " n a m e " :  " s o c i e t y " } ,  { " i d " :  3 8 0 1 ,  " n a m e " :  " s p a c e  t r a v e l " } ,  { " i d " :  9 6 8 5 ,  " n a m e " :  " f u t u r i s t i c " } ,  { " i d " :  9 8 4 0 ,  " n a m e " :  " r o m a n c e " } ,  { " i d " :  9 8 8 2 ,  " n a m e " :  " s p a c e " } ,  { " i d " :  9 9 5 1 ,  " n a m e " :  " a l i e n " } ,  { " i d " :  1 0 1 4 8 ,  " n a m e " :  " t r i b e " } ,  { " i d " :  1 0 1 5 8 ,  " n a m e " :  " a l i e n  p l a n e t " } ,  { " i d " :  1 0 9 8 7 ,  " n a m e " :  " c g i " } ,  { " i d " :  1 1 3 9 9 ,  " n a m e " :  " m a r i n e " } ,  { " i d " :  1 3 0 6 5 ,  " n a m e " :  " s o l d i e r " } ,  { " i d " :  1 4 6 4 3 ,  " n a m e " :  " b a t t l e " } ,  { " i d " :  1 4 7 2 0 ,  " n a m e " :  " l o v e  a f f a i r " } ,  { " i d " :  1 6 5 4 3 1 ,  " n a m e " :  " a n t i  w a r " } ,  { " i d " :  1 9 3 5 5 4 ,  " n a m e " :  " p o w e r  r e l a t i o n s " } ,  { " i d " :  2 0 6 6 9 0 ,  " n a m e " :  " m i n d  a n d  s o u l " } ,  { " i d " :  2 0 9 7 1 4 ,  " n a m e " :  " 3 d " } ] samworthington zoesaldana sigourneyweaver jamescameron'

In [26]:
import os
import pickle

os.makedirs("../artifacts", exist_ok=True)

pickle.dump(new_df, open("../artifacts/new_df_phase3.pkl", "wb"))
new_df.to_csv("../data/new_df_phase3.csv", index=False)

print("new_df saved as both pickle and CSV!")

new_df saved as both pickle and CSV!