# Text Preprocessing

In [1]:
import pickle
import pandas as pd
from nltk.stem.porter import PorterStemmer

In [2]:
# Load Phase 3 dataframe
new_df = pickle.load(open("../artifacts/new_df_phase3.pkl", "rb"))

print("Loaded dataframe shape:", new_df.shape)

Loaded dataframe shape: (4806, 3)

In [3]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [4]:
# Create stemmer object
ps = PorterStemmer()

In [ ]:
# Stemming function
def stem(text):
    stemmed_words = []

    for word in text.split():
        stemmed_words.append(ps.stem(word))

    return " ".join(stemmed_words)

In [6]:
# Apply stemming
new_df["tags"] = new_df["tags"].apply(stem)

In [7]:
# Check result
display(new_df.head())

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [8]:
# Save final processed dataframe
pickle.dump(new_df, open("../artifacts/new_df_final.pkl", "wb"))

print("Final processed dataframe saved successfully!")

Final processed dataframe saved successfully!